### ISSUE TITLE
Adding Easter & Other Weird Time Based Holiday Detection

### ISSUE THREAD

**Issue by Bowswa** [CMDred/TimeLib#3]
Hello!
I work on a lot of projects, and try to add holidays to be as inclusive of them as possible, giving things to celebrate. However, Holidays that act weird and change every year are hard to do in minecraft. How do you find these things out?

I'm not sure easter is the only one, but it is the one that comes to mind. I was wondering if adding this weird time based holiday detection would be in scope, or if it could be an addon pack, as i, an ignorant fool compared to you and other datapackers of your skill level, think that maybe some of the systems used to get the unix time conversion can be used to get some such holidays.

I just wanna be as inclusive as possible, and the static holidays are easy as pie, but i don't like that i can't include others.

**Comment by SilicatYT** [comment]
Hey there, thanks for reaching out!
I currently do not plan adding such special holidays, since they need to be added on a case-by-case basis and would add bloat to the pack for those who do not need them. I'm afraid you'll need to code the logic to calculate when the next XYZ holiday is yourself with commands.

In case of Easter, afaik it involves real life moon phases, so it might be quite difficult. Some other holidays may be simpler to implement. If you're having trouble, I suggest you make a help thread in the minecraft commands discord here: https://discord.gg/QAFXFtZ

I'm sure people would be willing to help further!
