### ISSUE TITLE
1.20.1 version?

### ISSUE THREAD

**Issue by vinnyg0621** [CMDred/TimeLib#4]
it doesn't work for me on that version 😞

**Comment by SilicatYT** [comment]
1.20.1 is not supported by TimeLib, and there are no plans of porting it backwards.

**Comment by vinnyg0621** [comment]
wait, why? that’s the only version i use, and i don’t use any newer versions than that one

**Comment by vinnyg0621** [comment]
why? please tell me!!

**Comment by SilicatYT** [comment]
Because it would require massive code changes to port the most recent TimeLib version over (as well as testing in all scenarios to make sure it works), and releasing an older version of TimeLib after a newer one is already available would mess with the changelogs.

Is there a reason you can't use 1.20.3+?

Edit: To elaborate, it *could* get ported to 1.20.2 with a bit of effort, but porting it to 1.20.1 is basically impossible because function macros don't exist in that version. It would require tons of hardcoding.
